name: Feature Request
description: Propose a new capability for the framework
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Propose features that improve safe simulation quality and operator workflows.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior and command/API shape.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: safety
    attributes:
      label: Safety confirmation
      options:
        - label: This request stays within authorized simulation and responsible-use boundaries.
          required: true
